--
DROP TABLE t1 CASCADE CONSTRAINTS PURGE;
DROP TABLE t2 CASCADE CONSTRAINTS PURGE;

CREATE TABLE t1 (c1 NUMBER, c2 NUMBER);
CREATE TABLE t2 (c0 NUMBER, c1 NUMBER, c2 NUMBER);

ALTER TABLE t1 ADD CONSTRAINT t1_pk PRIMARY KEY (c1, c2);
ALTER TABLE t2 ADD CONSTRAINT t2_pk PRIMARY KEY (c0);
ALTER TABLE t2 ADD CONSTRAINT t2_f1 FOREIGN KEY (c1, c2) REFERENCES t1 (c1, c2);

INSERT INTO t1 VALUES (1, 1);
INSERT INTO t1 VALUES (2, 2);
COMMIT;

--
INSERT INTO t2 VALUES (1, 1   , 1   );
INSERT INTO t2 VALUES (2, 1   , 2   );
INSERT INTO t2 VALUES (3, 1   , NULL);
INSERT INTO t2 VALUES (4, 2   , NULL);
INSERT INTO t2 VALUES (5, 3   , NULL);
INSERT INTO t2 VALUES (6, NULL, 2   );
INSERT INTO t2 VALUES (7, NULL, NULL);

--
SELECT * FROM t2;

--
ALTER TABLE t2 ADD CONSTRAINT t2_c1
CHECK ((c1 IS NULL AND c2 IS NULL) OR (c1 IS NOT NULL AND c2 IS NOT NULL));

--
INSERT INTO t2 VALUES (1, 1   , 1   );
INSERT INTO t2 VALUES (2, 1   , 2   );
INSERT INTO t2 VALUES (3, 1   , NULL);
INSERT INTO t2 VALUES (4, 2   , NULL);
INSERT INTO t2 VALUES (5, 3   , NULL);
INSERT INTO t2 VALUES (6, NULL, 2   );
INSERT INTO t2 VALUES (7, NULL, NULL);

--
SELECT * FROM t2;

--
ROLLBACK;
ALTER TABLE t2 DROP CONSTRAINT t2_c1;

--
CREATE OR REPLACE TRIGGER trg_t2_b_iu_1
    BEFORE INSERT OR UPDATE OF c1, c2 ON t2 FOR EACH ROW
DECLARE
    l_c1    NUMBER    := 1;
    l_c2    NUMBER    := 1;
BEGIN
    IF :NEW.c1 IS NOT NULL AND (INSERTING OR UPDATING ('c1')) THEN
        SELECT COUNT (1) INTO l_c1 FROM t1 WHERE c1 = :NEW.c1 AND ROWNUM <= 1;
    END IF;

    IF :NEW.c2 IS NOT NULL AND (INSERTING OR UPDATING ('c2')) THEN
        SELECT COUNT (1) INTO l_c2 FROM t1 WHERE c2 = :NEW.c2 AND ROWNUM <= 1;
    END IF;

    IF 0 IN (l_c1, l_c2) THEN
        RAISE_APPLICATION_ERROR (-20001, '무결성 제약 조건에 위배됩니다- 부모 키가 없습니다');
    END IF;
END;

--
INSERT INTO t2 VALUES (1, 1   , 1   );
INSERT INTO t2 VALUES (2, 1   , 2   );
INSERT INTO t2 VALUES (3, 1   , NULL);
INSERT INTO t2 VALUES (4, 2   , NULL);
INSERT INTO t2 VALUES (5, 3   , NULL);
INSERT INTO t2 VALUES (6, NULL, 2   );
INSERT INTO t2 VALUES (7, NULL, NULL);
COMMIT;

--
SELECT * FROM t2;

--
DELETE FROM t1 WHERE c1 = 1 AND c2 = 1;

DELETE FROM t1 WHERE c1 = 2 AND c2 = 2;

--
ROLLBACK;

--
CREATE OR REPLACE TRIGGER trg_t1_b_ud_1
    BEFORE UPDATE OF c1, c2 OR DELETE ON t1 FOR EACH ROW
DECLARE
    v_c1 NUMBER := 0;
    v_c2 NUMBER := 0;
BEGIN
    IF DELETING OR UPDATING ('c1') THEN
        SELECT COUNT (1) INTO v_c1 FROM t2 WHERE c1 = :OLD.c1 AND ROWNUM <= 1;
    END IF;

    IF DELETING OR UPDATING ('c2') THEN
        SELECT COUNT (1) INTO v_c2 FROM t2 WHERE c2 = :OLD.c2 AND ROWNUM <= 1;
    END IF;

    IF 1 IN (v_c1, v_c2) THEN
        RAISE_APPLICATION_ERROR (-20002, '무결성 제약 조건에 위배됩니다- 자식 레코드가 발견되었습니다');
    END IF;
END;
/

--
DELETE FROM t1 WHERE c1 = 2 AND c2 = 2;
