--
SELECT * FROM t1 WHERE c2 IS A SET;

--
SELECT * FROM t1 WHERE c2 IS EMPTY;

--
SELECT * FROM t1 WHERE c2 IS A SET AND c2 IS NOT EMPTY;

--
SELECT * FROM t1 WHERE 2 MEMBER OF c2;

--
SELECT * FROM t1 WHERE tnt1 (1, 3) SUBMULTISET OF c2;
