--
SELECT SET (tnt1 (1, 2, 2)) AS c1
     , SET (tnt2 (trc1 (1, 1), trc1 (2, 2), trc1 (2, 2))) AS c2
  FROM DUAL;

--
SELECT CARDINALITY (tnt1 (1, 2, 3)) AS c1
     , CARDINALITY (tnt2 (trc1 (1, 1), trc1 (2, 2), trc1 (2, 2))) AS c2
  FROM DUAL;

--
SELECT POWERMULTISET (tnt1 (1, 2, 3)) AS c1 FROM DUAL;

--
SELECT CAST (POWERMULTISET (tnt1 (1, 2, 3)) AS tnt3) AS c1 FROM DUAL;

--
SELECT CAST (POWERMULTISET_BY_CARDINALITY (tnt1 (1, 2, 3), 2) AS tnt3) AS c1 FROM DUAL;

--
DROP TABLE t2 PURGE;
CREATE TABLE t2 (c1 NUMBER);

INSERT INTO t2 VALUES (2);
INSERT INTO t2 VALUES (2);
INSERT INTO t2 VALUES (1);
COMMIT;

--
SELECT COLLECT (c1) AS c1 FROM t2;

--
SELECT type_name, typecode, instantiable
  FROM user_types
 WHERE type_name = 'ST00001lDX3R79QMqeFNW/B5BITQ=';

--
SELECT CAST (COLLECT (c1) AS tnt1) AS c1 FROM t2;

--
SELECT CAST (COLLECT (DISTINCT c1) AS tnt1) AS c1 FROM t2;

--
SELECT CAST (COLLECT (c1 ORDER BY c1) AS tnt1) AS c1 FROM t2;

--
SELECT CAST (COLLECT (DISTINCT c1 ORDER BY c1) AS tnt1) AS c1 FROM t2;

--
SELECT CAST (MULTISET (SELECT c1 FROM t2) AS tnt1) AS c1 FROM DUAL;

--
SELECT CAST (MULTISET (SELECT DISTINCT c1 FROM t2 ORDER BY c1) AS tnt1) AS c1 FROM DUAL;
