--
DROP TABLE t1 PURGE;
CREATE TABLE t1 AS SELECT TO_CLOB ('°¡123') AS c1, TO_CLOB ('°¡123') AS c2 FROM DUAL;

--
SELECT * FROM t1 WHERE c1 = c2;

--
SELECT * FROM t1 WHERE DBMS_LOB.COMPARE (c1, c2) = 0;

--
SELECT DBMS_LOB.GETLENGTH (c1) AS c1, LENGTH (c1) AS c2 FROM t1;

--
SELECT DBMS_LOB.INSTR (c1, '1') AS c1, INSTR (c1, '1') AS c2 FROM t1;

--
SELECT DBMS_LOB.SUBSTR (c1, 2, 1) AS c1, SUBSTR (c1, 1, 2) AS c2 FROM t1;
