--
DROP TABLE t1 PURGE;
CREATE TABLE t1 (c1 NUMBER, c2 NUMBER, CONSTRAINT t1_pk PRIMARY KEY (c1));

--
SELECT DBMS_METADATA.GET_DDL ('TABLE', 'T1', 'SCOTT') AS c1 FROM DUAL;

--
SELECT DBMS_METADATA.GET_DDL ('INDEX', 'T1_PK', 'SCOTT') AS c1 FROM DUAL;

--
DECLARE
    l_th NUMBER := DBMS_METADATA.SESSION_TRANSFORM;
BEGIN
    DBMS_METADATA.SET_TRANSFORM_PARAM (l_th, 'PRETTY'            , FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM (l_th, 'SQLTERMINATOR'     , TRUE);
    DBMS_METADATA.SET_TRANSFORM_PARAM (l_th, 'CONSTRAINTS'       , FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM (l_th, 'SEGMENT_ATTRIBUTES', FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM (l_th, 'STORAGE'           , FALSE);
END;
/

--
SELECT DBMS_METADATA.GET_DDL ('TABLE', 'T1', 'SCOTT') AS c1 FROM DUAL;
