--
SELECT UTL_MATCH.EDIT_DISTANCE ('ABCDEF', 'A1C2E3') AS c1 FROM DUAL;

--
SELECT UTL_MATCH.EDIT_DISTANCE_SIMILARITY ('ABCDEF', 'A1C2E3') AS c1 FROM DUAL;

--
SELECT UTL_MATCH.JARO_WINKLER ('ABCDEF', 'A1C2E3') AS c1 FROM DUAL;

--
SELECT UTL_MATCH.JARO_WINKLER_SIMILARITY ('ABCDEF', 'A1C2E3') AS c1 FROM DUAL;
