# server port
# web.xml
# session(1800 seconds = 30 minutes)
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800

# servlet-context.xml
# database connection
spring:
  web:
    resources:
      static-locations: /resources/**
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: SHAREGRAM
      password: 1111

# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml