--
DROP TABLE t1 PURGE;
DROP TABLE t2 PURGE;

CREATE TABLE t1 (c1 VARCHAR2 (1) NOT NULL, c2 NUMBER);
CREATE TABLE t2 (c1 VARCHAR2 (1) NOT NULL, c2 NUMBER);

INSERT INTO t1 (c1, c2) VALUES ('A', 1);
INSERT INTO t1 (c1, c2) VALUES ('A', 2);
INSERT INTO t1 (c1, c2) VALUES ('B', 1);
INSERT INTO t1 (c1, c2) VALUES ('B', 2);
INSERT INTO t1 (c1, c2) VALUES ('Z', NULL);
INSERT INTO t2 (c1, c2) VALUES ('B', 1);
INSERT INTO t2 (c1, c2) VALUES ('B', 1);
INSERT INTO t2 (c1, c2) VALUES ('B', 2);
INSERT INTO t2 (c1, c2) VALUES ('C', 2);
INSERT INTO t2 (c1, c2) VALUES ('Z', NULL);
COMMIT;

--
SELECT c1 FROM t1;

SELECT c1 FROM t2;

--
SELECT c1, c2 FROM t1;

SELECT c1, c2 FROM t2;
