DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD(
	BOARD_NO NUMBER NOT NULL,
	WRITER VARCHAR2(30 BYTE) NOT NULL,
	TITLE VARCHAR2(100 BYTE),
	CONTENT VARCHAR2(1000 BYTE),
	CREATE_DATE DATE
);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '관리자' , '공지사항' , '시험' , SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '관리자' , '긴급공지' , '망했다' , SYSDATE);
COMMIT;