--
DROP TABLE t1 PURGE;

CREATE TABLE t1 AS
SELECT LPAD (CEIL (ROWNUM / 10), 10, '0') AS c1 FROM XMLTABLE ('1 to 10000000');

--
SET TIMING ON

--
SELECT APPROX_COUNT_DISTINCT (c1) AS c1 FROM t1;

SELECT COUNT (DISTINCT c1) AS c1 FROM t1;

--
DROP TABLE t1 PURGE;

CREATE TABLE t1 AS
SELECT   TO_CHAR (hiredate, 'YYYY') AS yyyy, TO_CHAR (hiredate, 'MM') AS mm
       , APPROX_COUNT_DISTINCT_DETAIL (deptno) AS c1
    FROM emp
GROUP BY TO_CHAR (hiredate, 'YYYY'), TO_CHAR (hiredate, 'MM');

--
SELECT * FROM t1;

--
SELECT   yyyy, TO_APPROX_COUNT_DISTINCT (APPROX_COUNT_DISTINCT_AGG (c1)) AS c1
    FROM t1
GROUP BY yyyy;

--
SELECT   mm, TO_APPROX_COUNT_DISTINCT (APPROX_COUNT_DISTINCT_AGG (c1)) AS c1
    FROM t1
GROUP BY mm;

--
SELECT APPROX_PERCENTILE (0.5) WITHIN GROUP (ORDER BY sal)               AS c1
     , APPROX_PERCENTILE (0.5) WITHIN GROUP (ORDER BY hiredate)          AS c2
     , APPROX_PERCENTILE (0.5 DETERMINISTIC) WITHIN GROUP (ORDER BY sal) AS c3
     , APPROX_PERCENTILE (0.5, 'ERROR_RATE') WITHIN GROUP (ORDER BY sal) AS c4
     , APPROX_PERCENTILE (0.5, 'CONFIDENCE') WITHIN GROUP (ORDER BY sal) AS c5
  FROM emp
 WHERE deptno = 30;

--
DROP TABLE t1 PURGE;

CREATE TABLE t1 AS
SELECT   TO_CHAR (hiredate, 'YYYY') AS yyyy, TO_CHAR (hiredate, 'MM') AS mm
       , APPROX_PERCENTILE_DETAIL (sal) AS c1
    FROM emp
GROUP BY TO_CHAR (hiredate, 'YYYY'), TO_CHAR (hiredate, 'MM');

--
SELECT * FROM t1;

--
SELECT   yyyy, TO_APPROX_PERCENTILE (APPROX_PERCENTILE_AGG (c1), 0.5, 'NUMBER') AS c1
    FROM t1
GROUP BY yyyy;

--
SELECT   mm, TO_APPROX_PERCENTILE (APPROX_PERCENTILE_AGG (c1), 0.5, 'NUMBER') AS c1
    FROM t1
GROUP BY mm;

--
SELECT APPROX_MEDIAN (sal)                             AS c1
     , APPROX_MEDIAN (hiredate)                        AS c2
     , APPROX_MEDIAN (sal DETERMINISTIC)               AS c3
     , APPROX_MEDIAN (sal DETERMINISTIC, 'ERROR_RATE') AS c4
     , APPROX_MEDIAN (sal DETERMINISTIC, 'CONFIDENCE') AS c5
  FROM emp
 WHERE deptno = 30;
