--
DROP TABLE t1 PURGE;

CREATE TABLE t1 (empno NUMBER(4), ename VARCHAR2(10), sal NUMBER(7,2)
               , CONSTRAINT t1_pk PRIMARY KEY (empno));

INSERT INTO t1 VALUES (7782, 'CLARK', 2450);
COMMIT;

--
EXEC DBMS_ERRLOG.CREATE_ERROR_LOG (dml_table_name => 'T1', err_log_table_name => 'E1')

--
DESC e1

--
INSERT INTO t1 VALUES (7839, 'KING', 100000);

INSERT INTO t1 VALUES (7782, 'CLARK', 2450);

INSERT INTO t1 SELECT empno, ename, sal FROM emp WHERE deptno = 10;

--
INSERT INTO t1 VALUES (7839, 'KING', 100000)
LOG ERRORS INTO e1 ('1') REJECT LIMIT UNLIMITED;

INSERT INTO t1 VALUES (7782, 'CLARK', 2450)
LOG ERRORS INTO e1 ('2') REJECT LIMIT UNLIMITED;

INSERT INTO t1 SELECT empno, ename, sal FROM emp WHERE deptno = 10
LOG ERRORS INTO e1 ('3') REJECT LIMIT UNLIMITED;

--
SELECT * FROM t1;

--
SELECT ora_err_mesg$, ora_err_optyp$, ora_err_tag$, empno, sal FROM e1;

--
DROP TABLE e1 PURGE;

--
DROP TABLE t1 PURGE;
CREATE TABLE t1 (c1 NUMBER, CONSTRAINT t1_u1 UNIQUE (c1));

INSERT INTO t1 VALUES (1);
COMMIT;

--
INSERT INTO t1 SELECT LEVEL FROM DUAL CONNECT BY LEVEL <= 2;

--
INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(T1 T1_U1) */
  INTO t1
SELECT LEVEL FROM DUAL CONNECT BY LEVEL <= 2;
