--
ALTER SESSION SET NLS_DATE_FORMAT         = "YYYY-MM-DD HH24:MI:SS";
ALTER SESSION SET NLS_TIMESTAMP_FORMAT    = "YYYY-MM-DD HH24:MI:SS.FF";
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = "YYYY-MM-DD HH24:MI:SS.FF TZH:TZM";

--
DROP TABLE t1 PURGE;

CREATE TABLE t1 (
    c1 TIMESTAMP, c2 TIMESTAMP WITH TIME ZONE, c3 TIMESTAMP WITH LOCAL TIME ZONE);

--
SELECT column_name, data_type, data_length, data_scale
  FROM user_tab_columns
 WHERE table_name = 'T1';

--
INSERT INTO t1 VALUES (TIMESTAMP '2050-01-01 09:00:00 +09:00'
                     , TIMESTAMP '2050-01-01 09:00:00 +09:00'
                     , TIMESTAMP '2050-01-01 09:00:00 +09:00');

--
SELECT * FROM t1;

--
ALTER SESSION SET TIME_ZONE = '+08:00';

--
SELECT * FROM t1;

--
WITH w1 AS (SELECT TIMESTAMP '2050-01-01 00:00:00 Asia/Seoul' AS c1 FROM DUAL)
SELECT EXTRACT (TIMEZONE_HOUR   FROM c1) AS c1
     , EXTRACT (TIMEZONE_MINUTE FROM c1) AS c2
     , EXTRACT (TIMEZONE_REGION FROM c1) AS c3
     , EXTRACT (TIMEZONE_ABBR   FROM c1) AS c4
  FROM w1;

--
SELECT TZ_OFFSET ('Asia/Seoul')    AS c1
     , TZ_OFFSET (SESSIONTIMEZONE) AS c2
     , TZ_OFFSET (DBTIMEZONE)      AS c3
  FROM DUAL;

--
SELECT tzname, tzabbrev FROM v$timezone_names;

--
SELECT DBTIMEZONE AS c1 FROM DUAL;

--
SELECT SESSIONTIMEZONE AS c1, DBTIMEZONE AS c2 FROM DUAL;

--
SELECT CURRENT_DATE AS c1, SYSDATE AS c2 FROM DUAL;

--
SELECT CURRENT_TIMESTAMP AS c1, SYSTIMESTAMP AS c2 FROM DUAL;

--
SELECT LOCALTIMESTAMP AS c1, CURRENT_TIMESTAMP AS c2 FROM DUAL;

--
SELECT FROM_TZ (TIMESTAMP '2050-01-01 00:00:00', '+09:00') AS c1 FROM DUAL;

--
SELECT SYS_EXTRACT_UTC (TIMESTAMP '2050-01-01 09:00:00 +09:00') AS c1 FROM DUAL;

--
SELECT NEW_TIME (DATE '2050-01-01', 'PST', 'GMT') AS c1 FROM DUAL;

--
SELECT TO_TIMESTAMP_TZ ('2050-01-02 12 +08:00', 'YYYY-MM-DD HH24 TZH:TZM') AS c1 FROM DUAL;

--
SELECT c1, c1 AT TIME ZONE '+09:00' AS c2 FROM t1;
