--
SELECT LISTAGG (ename, ',') WITHIN GROUP (ORDER BY ename) AS c1
  FROM emp
 WHERE deptno = 30;

--
WITH w1 AS (SELECT 'X' AS c1 FROM DUAL CONNECT BY LEVEL <= 4001)
SELECT LISTAGG (c1) WITHIN GROUP (ORDER BY NULL) AS c1 FROM w1;

--
WITH w1 AS (SELECT 'X' AS c1 FROM DUAL CONNECT BY LEVEL <= 4001)
SELECT LISTAGG (c1 ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY NULL) AS c1 FROM w1;
