-- 시퀀스
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO NUMBER NOT NULL,
    TITLE VARCHAR2(100 BYTE) NOT NULL,
    CONTENT VARCHAR2(400 BYTE),
    CREATE_DATE DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
    );

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '공지', '불났다', SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '긴급공지', '다 날라갔다.', SYSDATE);
COMMIT; 